default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bassemshaker_development

test:
  <<: *default
  database: bassemshaker_test

production:
  <<: *default
  database: bassemshaker_production
  username: bassemshaker
  password: <%= ENV['BASSEMSHAKER_DATABASE_PASSWORD'] %>
