# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 268193dea2ef898b0c79d376a1eeae180eef5d85d941400b1ba5891fdc9b6a9fa2c965c398c4a30ccff85cc46401ae0160eee30f133dff023b50a6d9e157bd16

test:
  secret_key_base: 4098b5dca1c93961dccc6ce90d30b8ec299ff4c2d84b3abc5cd374fc7331ae651bd41dd08377d676d356a3d4bc5ee3ae7724c6b4dcfd54424edb65daa9af86cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
